apiVersion: batch/v1
kind: Job
metadata:
  name: hhh-job-train-bv2-billy-v61-continue-val
  labels:
    jobgroup: hhh-job-train
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                - k8s-a100-01.suncorridor.org 

              - key: nvidia.com/gpu.product  
                operator: In
                values:
                - NVIDIA-A100-SXM4-80GB
                - NVIDIA-A100-80GB-PCIe
                - NVIDIA-A100-PCIE-40GB

      containers:
        - name: training
          image: gitlab-registry.nrp-nautilus.io/jmduarte/hhh:latest
          command:
            - "/bin/bash"
            - "-c"
            - >
              cp -r /opt/repo/SPANet . &&
              cd SPANet &&
              pip install -e . &&
              cd /hhh-vol &&
              python -m spanet.train -of /hhh-vol/options_files/delphes/continue_test/test.json -l /hhh-vol/logs/continue_test/ -n assign_5_val --epochs 4000 --gpus 1 --batch_size 4096 -sf /hhh-vol/logs/bv2/version_61/checkpoints/last.ckpt
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - mountPath: /hhh-vol
              name: hhh-vol
            - name: git-repo
              mountPath: /opt/repo
          resources:
            limits:
              memory: 32Gi
              cpu: "8"
              nvidia.com/gpu: "1"
            requests:
              memory: 32Gi
              cpu: "8"
              nvidia.com/gpu: "1"
      initContainers:
        - name: init-clone-repo
          image: alpine/git
          args:
            - clone
            - --single-branch
            - https://github.com/billy000400/SPANet
            - -b
            - balance_acc
            - --recurse-submodules
            - /opt/repo/SPANet
          volumeMounts:
            - name: git-repo
              mountPath: /opt/repo
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 16Gi
        - name: git-repo
          emptyDir: {}
        - name: hhh-vol
          persistentVolumeClaim:
            claimName: hhh-vol
      restartPolicy: Never
  backoffLimit: 5
