apiVersion: v1
kind: Pod
metadata:
  name: hhh-pod-billy-any
  labels:
    app: hhh
spec:
  containers:
  - name: container
    image: gitlab-registry.nrp-nautilus.io/jmduarte/hhh:latest
    command: 
      - "/bin/bash"
      - "-c"
      - >
       git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim &&
       curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim &&
       git clone https://github.com/billy000400/vim &&
       cp vim/.vimrc . && 
       vi +PlugInstall +PluginInstall +qall &&
       sleep 36500000
    resources:
      limits:
        memory: 16Gi
        cpu: "4"
        nvidia.com/gpu: "1"
      requests:
        memory: 16Gi
        cpu: "4"
        nvidia.com/gpu: "1"
    volumeMounts:
    - mountPath: /hhh-vol
      name: hhh-vol
    - mountPath: /dev/shm
      name: dshm
  volumes:
    - name: hhh-vol
      persistentVolumeClaim:
        claimName: hhh-vol
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 8Gi
