apiVersion: batch/v1
kind: Job
metadata:
  name: hhh-job-test-v2-billy
  labels:
    jobgroup: hhh-job-test
spec:
  template:
    spec:
      containers:
        - name: testing
          image: gitlab-registry.nrp-nautilus.io/jmduarte/hhh:latest
          command:
            - "python"
          args:
            - "-m"
            - "spanet.test"
            - "/hhh-vol/logs/v20_output/version_26"
            - -tf
            - "/hhh-vol/data/delphes/v20-random-seed/hhh_testing.h5"
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - mountPath: /hhh-vol
              name: hhh-vol
            - name: git-repo
              mountPath: /opt/repo
          resources:
            limits:
              memory: 32Gi
              cpu: "8"
              nvidia.com/gpu: "1"
            requests:
              memory: 16Gi
              cpu: "4"
              nvidia.com/gpu: "1"
      initContainers:
        - name: init-clone-repo
          image: alpine/git
          args:
            - clone
            - --single-branch
            - https://github.com/ucsd-hep-ex/hhh
            - -b
            - main
            - --recurse-submodules
            - /opt/repo/hhh
          volumeMounts:
            - name: git-repo
              mountPath: /opt/repo
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 8Gi
        - name: git-repo
          emptyDir: {}
        - name: hhh-vol
          persistentVolumeClaim:
            claimName: hhh-vol
      restartPolicy: Never
  backoffLimit: 5
