apiVersion: batch/v1
kind: Job
metadata:
  name: hhh-job-train-v20-billy-default
  labels:
    jobgroup: hhh-job-train
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-GeForce-RTX-3090
      containers:
        - name: training
          image: gitlab-registry.nrp-nautilus.io/jmduarte/hhh:latest
          command:
            - "python"
          args:
            - "-m"
            - "spanet.train"
            - -of
            - "/hhh-vol/options_files/cms/hhh_v26_boosted.json"
            - -l
            - "/hhh-vol/logs/"
            - -n
            - "v26_output"
            - --epochs
            - "2000"
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - mountPath: /hhh-vol
              name: hhh-vol
            - name: git-repo
              mountPath: /opt/repo
          resources:
            limits:
              memory: 32Gi
              cpu: "8"
              nvidia.com/gpu: "1"
            requests:
              memory: 32Gi
              cpu: "8"
              nvidia.com/gpu: "1"
      initContainers:
        - name: init-clone-repo
          image: alpine/git
          args:
            - clone
            - --single-branch
            - https://github.com/ucsd-hep-ex/hhh
            - -b
            - main
            - --recurse-submodules
            - /opt/repo/hhh
          volumeMounts:
            - name: git-repo
              mountPath: /opt/repo
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 8Gi
        - name: git-repo
          emptyDir: {}
        - name: hhh-vol
          persistentVolumeClaim:
            claimName: hhh-vol
      restartPolicy: Never
  backoffLimit: 5
