apiVersion: batch/v1
kind: Job
metadata:
  name: hhh-billy-hyperopt-4gpu-no-continuous
  labels:
    jobgroup: hhh-job-train
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-A10
                - NVIDIA-GeForce-RTX-3090
                - NVIDIA-GeForce-RTX-4090
                - NVIDIA-TITAN-RTX
                - NVIDIA-RTX-A5000
                - Quadro-RTX-6000
                - Tesla-V100-SXM2-32GB
                - NVIDIA-A40
                - NVIDIA-RTX-A6000
                - Quadro-RTX-8000
      containers:
        - name: training
          image: gitlab-registry.nrp-nautilus.io/jmduarte/hhh:latest
          command:
            - "/bin/bash"
            - "-c"
            - >
             git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim &&
             mkdir -p ~/.vim/autoload/ &&
             wget -O ~/.vim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim &&
             git clone https://github.com/billy000400/vim &&
             cp vim/.vimrc ~/. && 
             vi +PlugInstall +PluginInstall +qall &&
             pip install ray[tune] ray[train] hyperopt &&
             git clone https://github.com/billy000400/SPANet &&
             cd SPANet &&
             pip install . &&
             python -m spanet.tune /hhh-vol/options_files/delphes/hhh_v2_boosted_base_1024.json -s /hhh-vol/search_space_files/tune_v1_no_continuous.json -g 1 -c 4 -e 100 -t 1000 -l /hhh-vol/tune/test/version1 -n tune_v1
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - mountPath: /hhh-vol
              name: hhh-vol
          resources:
            limits:
              memory: 64Gi
              cpu: "26"
              nvidia.com/gpu: "4"
            requests:
              memory: 64Gi
              cpu: "26"
              nvidia.com/gpu: "4"
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 32Gi
        - name: hhh-vol
          persistentVolumeClaim:
            claimName: hhh-vol
      restartPolicy: Never
  backoffLimit: 5
