apiVersion: batch/v1
kind: Job
metadata:
  name: hhh-job-billy-test-image-4-a10-base-dev2
  labels:
    jobgroup: hhh-job-train
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-A10
      containers:
        - name: training
          image: billy000400/hhh:latest 
          command:
            - "conda"
            - "run"
            - "-n"
            - "base"
            - "--live-stream"
            - "/bin/bash"
            - "-c"
            - >
             git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim &&
             mkdir -p ~/.vim/autoload/ &&
             wget -O ~/.vim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim &&
             git clone https://github.com/billy000400/vim &&
             cp vim/.vimrc ~/. && 
             vi +PlugInstall +PluginInstall +qall &&
             pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 &&
             pip install pytorch_lightning ray[tune] ray[train] hyperopt &&
             git clone https://github.com/billy000400/SPANet &&
             cd SPANet &&
             pip install . &&
             sleep 7d
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - mountPath: /hhh-vol
              name: hhh-vol
          resources:
            limits:
              memory: 64Gi
              cpu: "40"
              nvidia.com/gpu: "4"
            requests:
              memory: 64Gi
              cpu: "40"
              nvidia.com/gpu: "4"
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 32Gi
        - name: hhh-vol
          persistentVolumeClaim:
            claimName: hhh-vol
      restartPolicy: Never
  backoffLimit: 5
