apiVersion: v1
kind: Pod
metadata:
  name: hhh-pod-billy-test-image-no-conda
  labels:
    app: hhh
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: nvidia.com/gpu.product
            operator: In
            values:
            - NVIDIA-GeForce-RTX-3090
  containers:
  - name: container
    image: billy000400/hhh:latest
    command: 
      - "/bin/bash"
      - "-c"
      - >
       git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim &&
       mkdir -p ~/.vim/autoload/ &&
       wget -O ~/.vim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim &&
       git clone https://github.com/billy000400/vim &&
       cp vim/.vimrc ~/. && 
       vi +PlugInstall +PluginInstall +qall &&
       python -m spanet.tune /hhh-vol/options_files/delphes/hhh_v2_boosted_base.json -s /hhh-vol/search_space_files/hidden_dim.json -g 1 -e 100 -t 5 -l /hhh-vol/tune -n hidden_dim &&
       sleep 36500000
    resources:
      limits:
        memory: 16Gi
        cpu: "4"
        nvidia.com/gpu: "1"
      requests:
        memory: 16Gi
        cpu: "4"
        nvidia.com/gpu: "1"
    volumeMounts:
    - mountPath: /hhh-vol
      name: hhh-vol
    - mountPath: /dev/shm
      name: dshm
  volumes:
    - name: hhh-vol
      persistentVolumeClaim:
        claimName: hhh-vol
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 8Gi
