apiVersion: batch/v1
kind: Job
metadata:
  name: hhh-test-image-hyper-param
  labels:
    jobgroup: hhh-job-train
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-GeForce-RTX-3090
      containers:
        - name: training
          image: jmduarte/hhh:pytorch2
          command: ["/bin/sh","-c"]
          args:
            - cd /hhh-vol &&
              python -m spanet.tune /hhh-vol/options_files/delphes/hhh_v2_boosted_base.json -g 1 -e 100 -t 5 -l /hhh-vol/tune -n bv2
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - mountPath: /hhh-vol
              name: hhh-vol
            - name: git-repo
              mountPath: /opt/repo
          resources:
            limits:
              memory: 32Gi
              cpu: "8"
              nvidia.com/gpu: "1"
            requests:
              memory: 32Gi
              cpu: "8"
              nvidia.com/gpu: "1"
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 8Gi
        - name: git-repo
          emptyDir: {}
        - name: hhh-vol
          persistentVolumeClaim:
            claimName: hhh-vol
      restartPolicy: Never
  backoffLimit: 5
