apiVersion: v1
kind: Pod
metadata:
  name: hhh-delphes-test-data1
  labels:
    app: hhh
spec:
  containers:
  - name: container
    image: gitlab-registry.nrp-nautilus.io/jmduarte/hhh:latest
    command: 
      - "/bin/bash"
      - "-c"
      - >
        cd /hhh-vol/hhh/ &&
        pip install -e . &&
        python -m src.data.delphes.convert_to_h5 --out-file /hhh-vol/data/delphes/v2/hhh_test1.h5 --train-frac 0.98 /hhh-vol/data/delphes/v2/GF_HHH_SM_c3_0_d4_0_14TeV/sample_*.root
    resources:
      limits:
        memory: 32Gi
        cpu: "8"
        nvidia.com/gpu: "1"
      requests:
        memory: 16Gi
        cpu: "4"
        nvidia.com/gpu: "1"
    volumeMounts:
    - mountPath: /hhh-vol
      name: hhh-vol
  volumes:
    - name: hhh-vol
      persistentVolumeClaim:
        claimName: hhh-vol
  restartPolicy: Never
