apiVersion: batch/v1
kind: Job
metadata:
  name: hhh-job-hyper-param-bv2-billy-4gpu
  labels:
    jobgroup: hhh-job-train
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-GeForce-RTX-3090
      containers:
        - name: training
          image: gitlab-registry.nrp-nautilus.io/jmduarte/hhh:latest
          command: ["/bin/sh","-c"]
          args:
            - cp -r /opt/repo/SPANet . &&
              cd SPANet &&
              conda env create -p ./environment --file environment_cuda118.yaml &&
              conda activate ./environment &&
              cd /hhh-vol &&
              python -m spanet.tune /hhh-vol/options_files/delphes/hhh_v2_boosted_base.json -s /hhh-vol/search_space_files/test.json -g 4 -e 100 -t 5 -l /hhh-vol/tune -n bv2
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - mountPath: /hhh-vol
              name: hhh-vol
            - name: git-repo
              mountPath: /opt/repo
          resources:
            limits:
              memory: 32Gi
              cpu: "48"
              nvidia.com/gpu: "4"
            requests:
              memory: 32Gi
              cpu: "48"
              nvidia.com/gpu: "4"
      initContainers:
        - name: init-clone-repo
          image: alpine/git
          args:
            - clone
            - --single-branch
            - https://github.com/Alexanders101/SPANet 
            - -b
            - master
            - --recurse-submodules
            - /opt/repo/SPANet
          volumeMounts:
            - name: git-repo
              mountPath: /opt/repo
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 64Gi
        - name: git-repo
          emptyDir: {}
        - name: hhh-vol
          persistentVolumeClaim:
            claimName: hhh-vol
      restartPolicy: Never
  backoffLimit: 5
