apiVersion: batch/v1
kind: Job
metadata:
  name: hhh-job-train-bv2-billy-4gpu-diverge
  labels:
    jobgroup: hhh-job-train
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product  
                operator: NotIn
                values:
                - NVIDIA-A100-80GB-PCIe-MIG-1g.10gb 
      containers:
        - name: training
          image: gitlab-registry.nrp-nautilus.io/jmduarte/hhh:latest
          command: ["/bin/sh","-c"]
          args:
            - cp -r /opt/repo/SPANet . &&
              cd SPANet &&
              pip install -e . &&
              cd /hhh-vol &&
              python -m spanet.train -of /hhh-vol/tune/bv2/spanet_trial_9d9a0_00001_1_focal_gamma=0.6316,hidden_dim=96,l2_penalty=0.0001,learning_rate=0.0100,num_branch_embedding_layers=4,n_2023-08-15_17-17-31/hparams.json -l /hhh-vol/logs/ -n bv2 --epochs 2000 --gpus 4 --batch_size 4096
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - mountPath: /hhh-vol
              name: hhh-vol
            - name: git-repo
              mountPath: /opt/repo
          resources:
            limits:
              memory: 32Gi
              cpu: "8"
              nvidia.com/gpu: "4"
            requests:
              memory: 32Gi
              cpu: "8"
              nvidia.com/gpu: "4"
      initContainers:
        - name: init-clone-repo
          image: alpine/git
          args:
            - clone
            - --single-branch
            - https://github.com/billy000400/SPANet
            - -b
            - master
            - --recurse-submodules
            - /opt/repo/SPANet
          volumeMounts:
            - name: git-repo
              mountPath: /opt/repo
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 16Gi
        - name: git-repo
          emptyDir: {}
        - name: hhh-vol
          persistentVolumeClaim:
            claimName: hhh-vol
      restartPolicy: Never
  backoffLimit: 5
