apiVersion: batch/v1
kind: Job
metadata:
  name: hhh-job-train-bv2-billy-8gpu-a6000
  labels:
    jobgroup: hhh-job-train
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-RTX-A6000 
      containers:
        - name: training
          image: gitlab-registry.nrp-nautilus.io/jmduarte/hhh:latest
          command: ["/bin/sh","-c"]
          args:
            - cp -r /opt/repo/SPANet . &&
              cd SPANet &&
              pip install -e . &&
              cd /hhh-vol &&
              python -m spanet.train -of options_files/delphes/hhh_v2_boosted_best1.json -l /hhh-vol/logs/ -n bv2 --epochs 2000 --gpus 8 --batch_size 4096
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - mountPath: /hhh-vol
              name: hhh-vol
            - name: git-repo
              mountPath: /opt/repo
          resources:
            limits:
              memory: 32Gi
              cpu: "16"
              nvidia.com/gpu: "8"
            requests:
              memory: 32Gi
              cpu: "16"
              nvidia.com/gpu: "8"
      initContainers:
        - name: init-clone-repo
          image: alpine/git
          args:
            - clone
            - --single-branch
            - https://github.com/billy000400/SPANet
            - -b
            - master
            - --recurse-submodules
            - /opt/repo/SPANet
          volumeMounts:
            - name: git-repo
              mountPath: /opt/repo
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 32Gi
        - name: git-repo
          emptyDir: {}
        - name: hhh-vol
          persistentVolumeClaim:
            claimName: hhh-vol
      restartPolicy: Never
  backoffLimit: 5
